mono flavor
hiromotai7/meta-emlinux-flavors pull request #1
Opened 2024-10-02 10:56 UTC by takaaki-fukunaga

I have added mono flavor. Could you add these changes?

2024-10-05 07:12 UTC, takaaki-fukunaga commented
I have renamed How-to-Use.md to emlinux-image-mono.md and revised it for only Mono. 

I would like to add some flavoers and add **Confirm operation** section for each document. It's annoying to maintain each document but it's good for a user to understand how to use each flavor.

2024-10-10 11:23 UTC, hiromotai7 requested changes
Could you add this commit into 8d1c1a2f4f436cb1cd268bd4e3b33179070b43a1 by git-rebase?

2024-10-10 11:28 UTC, hiromotai7 requested changes
Could you add this commit into 787467f1c43c62cb5deb88a19a9174139f441766?

2024-10-10 11:35 UTC, hiromotai7 commented on recipes-core/images/emlinux-image-mono.bb
> +DESCRIPTION = "Gnome target root filesystem"
I would be happy if you used "emlinux-image-flavorname.bb.sample"....

2024-10-10 11:44 UTC, hiromotai7 commented
@takaaki-fukunaga Thanks.
I have made some comments and would be happy to correct them.

Finally, if you run "git diff a5c1be78dc41 <new>" and there is no difference between the current branch and new fixed branch, you can do "git push --force" the new branch as your/main branch. It means you do not need to make another merge request.

2024-12-12 14:02 UTC, takaaki-fukunaga commented
@hiromotai7 
I have rebased the main branch and pushed the changes. Could you check it when you have time?

2024-12-13 12:29 UTC, hiromotai7 commented
@takaaki-fukunaga 
Thank you. but you missed "sign-off-by" in commit 0e485e9213cd17c19b9574d723cf6583deac53bf.
Could you fix it?

2024-12-18 07:42 UTC, merged

2024-12-18 07:43 UTC, hiromotai7 commented
@takaaki-fukunaga 
Thanks!